### ISSUE TITLE
Create mail verification

### ISSUE THREAD

**Issue by gloria-stanciu** [OAMKpathfinder/group4#25]
- [x] After creating an account, the user should be redirected to a page where a confirmation code is required

- [x] Creating an HTML with EJS file that will be sent to the user's email account that will contain the required code

- [x] The received code should expire after 24h

Use [nodemailer](https://nodemailer.com/about/)

**Comment by arpadgabor** [comment]
![image](https://user-images.githubusercontent.com/9270494/69470238-e454a300-0d9d-11ea-8a9a-f8ab518ee8ca.png)
